#!/usr/bin/env python3
"""
etrade_auth.py — Standalone E*TRADE OAuth 1.0a authentication script.

Automates the full login flow:
  1. Request a temporary OAuth token from E*TRADE
  2. Open a headless Playwright browser, navigate to the authorization URL
  3. Enter username + password
  4. Enter the VIP 2FA code generated by python-vipaccess
  5. Capture the OAuth verifier code from the final page
  6. Exchange the verifier for a live access token + secret
  7. Write the token pair to .etrade_token.json

Run once per day (before market open) via scheduler or cron.
No human interaction required after one-time VIP credential setup.

Dependencies:
    pip install requests requests-oauthlib python-vipaccess playwright
    playwright install chromium

Required env vars (copy .env.etrade.example → .env.etrade and fill in):
    ETRADE_CONSUMER_KEY
    ETRADE_CONSUMER_SECRET
    ETRADE_USERNAME
    ETRADE_PASSWORD
    VIP_CREDENTIAL_ID       (from: vipaccess provision)
    VIP_SECRET              (from: vipaccess provision)
    ETRADE_SANDBOX          (set to "true" to use sandbox, "false" for live)
    TOKEN_OUTPUT_FILE       (optional, defaults to .etrade_token.json)
"""

import json
import os
import sys
import time
import logging
from pathlib import Path
from datetime import datetime, timezone

# ---------------------------------------------------------------------------
# Optional: auto-load .env.etrade if python-dotenv is available
# ---------------------------------------------------------------------------
try:
    from dotenv import load_dotenv
    _env_file = Path(__file__).parent / ".env.etrade"
    if _env_file.exists():
        load_dotenv(_env_file)
        print(f"[auth] Loaded env from {_env_file}")
except ImportError:
    pass  # dotenv not installed — rely on shell env vars

import requests
from requests_oauthlib import OAuth1

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("etrade_auth")

# ---------------------------------------------------------------------------
# Config — read from environment
# ---------------------------------------------------------------------------

CONSUMER_KEY    = os.environ.get("ETRADE_CONSUMER_KEY", "")
CONSUMER_SECRET = os.environ.get("ETRADE_CONSUMER_SECRET", "")
USERNAME        = os.environ.get("ETRADE_USERNAME", "")
PASSWORD        = os.environ.get("ETRADE_PASSWORD", "")
VIP_CRED_ID     = os.environ.get("VIP_CREDENTIAL_ID", "")
VIP_SECRET      = os.environ.get("VIP_SECRET", "")
SANDBOX         = os.environ.get("ETRADE_SANDBOX", "false").lower() == "true"
TOKEN_FILE      = os.environ.get("TOKEN_OUTPUT_FILE", str(Path(__file__).parent / ".etrade_token.json"))

# E*TRADE API base URLs
if SANDBOX:
    BASE_URL  = "https://apisb.etrade.com"
    AUTH_HOST = "https://us.etrade.com"
    log.info("Running in SANDBOX mode")
else:
    BASE_URL  = "https://api.etrade.com"
    AUTH_HOST = "https://us.etrade.com"
    log.info("Running in LIVE mode")

REQUEST_TOKEN_URL  = f"{BASE_URL}/oauth/request_token"
ACCESS_TOKEN_URL   = f"{BASE_URL}/oauth/access_token"
AUTHORIZE_URL      = f"{AUTH_HOST}/e/t/etws/authorize"


# ---------------------------------------------------------------------------
# Step 0: Validate config
# ---------------------------------------------------------------------------

def validate_config():
    missing = []
    for name, val in [
        ("ETRADE_CONSUMER_KEY",    CONSUMER_KEY),
        ("ETRADE_CONSUMER_SECRET", CONSUMER_SECRET),
        ("ETRADE_USERNAME",        USERNAME),
        ("ETRADE_PASSWORD",        PASSWORD),
        ("VIP_CREDENTIAL_ID",      VIP_CRED_ID),
        ("VIP_SECRET",             VIP_SECRET),
    ]:
        if not val:
            missing.append(name)
    if missing:
        log.error("Missing required environment variables: %s", ", ".join(missing))
        log.error("Copy .env.etrade.example → .env.etrade and fill in all values.")
        sys.exit(1)


# ---------------------------------------------------------------------------
# Step 1: Get request token
# ---------------------------------------------------------------------------

def get_request_token() -> tuple[str, str]:
    log.info("Requesting OAuth request token...")
    auth = OAuth1(
        CONSUMER_KEY,
        CONSUMER_SECRET,
        callback_uri="oob",  # out-of-band — we'll capture verifier from page DOM
    )
    resp = requests.get(REQUEST_TOKEN_URL, auth=auth, timeout=30)
    if resp.status_code != 200:
        log.error("Request token failed: %s %s", resp.status_code, resp.text)
        sys.exit(1)

    from urllib.parse import parse_qs
    params = {k: v[0] for k, v in parse_qs(resp.text).items()}
    req_token  = params["oauth_token"]
    req_secret = params["oauth_token_secret"]
    log.info("Got request token: %s…", req_token[:8])
    return req_token, req_secret


# ---------------------------------------------------------------------------
# Step 2: Generate VIP 2FA code
# ---------------------------------------------------------------------------

def get_vip_code() -> str:
    import base64, hmac, hashlib, struct
    # Decode base32 secret → raw bytes → hex (what oath.totp expects)
    raw = base64.b32decode(VIP_SECRET, casefold=True)
    t   = int(time.time()) // 30
    msg = struct.pack('>Q', t)
    h   = hmac.new(raw, msg, hashlib.sha1).digest()
    o   = h[-1] & 0xf
    code = (struct.unpack('>I', h[o:o+4])[0] & 0x7fffffff) % 1_000_000
    secs_left = 30 - (int(time.time()) % 30)
    log.info("Generated VIP code (valid ~%ds)", secs_left)
    return f"{code:06d}"


# ---------------------------------------------------------------------------
# Step 3: Playwright browser automation
# ---------------------------------------------------------------------------

def browser_authorize(req_token: str, vip_code: str) -> str:
    """
    Drive a headless Chromium browser through the E*TRADE login + 2FA flow
    and return the OAuth verifier code shown on the final page.

    E*TRADE login flow (confirmed from registration page):
      1. Enter username
      2. Enter password
      3. Check 'Use security code' checkbox
      4. Enter the 6-digit VIP code in the separate security code field
      5. Submit — lands on the OAuth verifier page
    """
    try:
        from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout
    except ImportError:
        log.error("playwright not installed. Run: pip install playwright && playwright install chromium")
        sys.exit(1)

    auth_url = f"{AUTHORIZE_URL}?key={CONSUMER_KEY}&token={req_token}"
    log.info("Navigating to authorization URL...")

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        ctx     = browser.new_context(
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/124.0.0.0 Safari/537.36"
            )
        )
        page = ctx.new_page()

        # ---- Navigate to auth URL ----
        page.goto(auth_url, wait_until="domcontentloaded", timeout=30_000)
        log.info("Page loaded: %s", page.url)

        # ---- Username ----
        try:
            page.wait_for_selector("#USER", timeout=15_000)
            page.fill("#USER", USERNAME)
            log.info("Filled username")
        except PWTimeout:
            _dump_page(page, "after_load")
            log.error("Could not find username field (#USER). Page structure may have changed.")
            browser.close()
            sys.exit(1)

        # ---- Password ----
        # Try multiple selectors — E*TRADE has used different IDs over time
        password_filled = False
        for pwd_sel in ["#PASSWORD", "input[type='password']", "#password", "input[name='PASSWORD']", "input[name='password']"]:
            try:
                page.wait_for_selector(pwd_sel, timeout=5_000)
                page.fill(pwd_sel, PASSWORD)
                log.info("Filled password via selector: %s", pwd_sel)
                password_filled = True
                break
            except Exception:
                continue
        if not password_filled:
            _dump_page(page, "no_password_field")
            log.error("Could not find password field. Check debug/ for snapshot.")
            browser.close()
            sys.exit(1)

        # ---- Check 'Use security code' checkbox ----
        try:
            checkbox = page.query_selector("input[id*='security'], input[name*='security'], #useSecurityCode, #USE_SECURITY_CODE")
            if checkbox:
                if not checkbox.is_checked():
                    checkbox.check()
                log.info("Checked 'Use security code' checkbox")
            else:
                log.info("No security code checkbox found — may appear after submit")
        except Exception as e:
            log.warning("Checkbox check skipped: %s", e)

        # ---- Submit login ----
        _dump_page(page, "before_submit")  # snapshot so we can inspect selectors
        submitted = False
        for btn_sel in ["#logon_button", "#btnLogon", "button[type='submit']", "input[type='submit']", "button:has-text('Log On')", "button:has-text('Login')", "button:has-text('Sign In')"]:
            try:
                page.click(btn_sel, timeout=4_000)
                log.info("Submitted login via: %s", btn_sel)
                submitted = True
                break
            except Exception:
                continue
        if not submitted:
            _dump_page(page, "no_submit_button")
            log.error("Could not find submit button. Check debug/ for snapshot.")
            browser.close()
            sys.exit(1)

        # ---- Wait for security code field (separate 2FA step) ----
        try:
            page.wait_for_selector(
                "input[id*='code'], input[name*='code'], input[id*='security'], input[name*='security']",
                timeout=15_000,
            )
            log.info("Security code field detected")

            # Generate a fresh VIP code right now — do NOT use the one generated
            # at startup; the browser flow takes ~30s and it may have expired.
            secs_remaining = 30 - (int(time.time()) % 30)
            if secs_remaining < 6:
                log.info("VIP code window ending in %ds — waiting for fresh window...", secs_remaining)
                time.sleep(secs_remaining + 1)
            vip_code = get_vip_code()
            log.info("Fresh VIP code ready (%ds remaining in window)", 30 - (int(time.time()) % 30))

            # Fill the VIP code
            code_sel = "input[id*='code'], input[name*='code'], input[id*='security'], input[name*='security']"
            page.fill(code_sel, vip_code)
            log.info("Filled VIP security code")

            # Submit the 2FA step — same button selectors as the first login submit
            submitted_2fa = False
            for btn in ["#logon_button", "#btnLogon", "button[type='submit']", "input[type='submit']",
                        "button:has-text('Log On')", "button:has-text('Login')", "button:has-text('Continue')", "#continueButton"]:
                try:
                    page.click(btn, timeout=4_000)
                    log.info("Clicked 2FA submit: %s", btn)
                    submitted_2fa = True
                    break
                except Exception:
                    continue

            if not submitted_2fa:
                _dump_page(page, "no_2fa_submit")
                log.error("Could not find 2FA submit button.")
                browser.close()
                sys.exit(1)

            # Wait for navigation away from the login page
            try:
                page.wait_for_url("**/authorize**", timeout=20_000)
                log.info("Navigated to verifier page: %s", page.url)
            except Exception:
                # May have already landed there
                page.wait_for_load_state("domcontentloaded", timeout=10_000)

        except PWTimeout:
            # No separate 2FA field appeared — check if we're already on verifier page
            log.info("No separate 2FA field — checking for verifier directly...")

        # ---- Authorization consent page — click Accept ----
        # E*TRADE shows a "Indicate Terms Agreement" page with an Accept button.
        # Must click it before the verifier code is revealed.
        try:
            page.wait_for_selector("#acceptSubmit", timeout=10_000)
            log.info("Authorization consent page detected — clicking Accept")
            page.click("#acceptSubmit")
            page.wait_for_load_state("domcontentloaded", timeout=15_000)
        except Exception as e:
            log.info("No consent page (or already accepted): %s", e)

        # ---- Snapshot and extract verifier ----
        _dump_page(page, "verifier_page")

        verifier = _try_extract_verifier(page)
        if not verifier:
            _dump_page(page, "after_login")
            log.error("Could not extract OAuth verifier. Check debug/ folder for page snapshot.")
            browser.close()
            sys.exit(1)

        browser.close()
        return verifier


def _try_extract_verifier(page) -> str | None:
    """Try several known DOM locations where E*TRADE shows the verifier code."""

    # Method 1: E*TRADE puts the verifier in a plain <input type="text"> on the
    # "Complete Authorization" page — this is the most reliable selector.
    try:
        # Wait briefly for the input to appear
        page.wait_for_selector("input[type='text']", timeout=5_000)
        els = page.query_selector_all("input[type='text']")
        for el in els:
            val = (el.get_attribute("value") or "").strip()
            if val and len(val) >= 4:
                log.info("Verifier found in input[type='text']: %s…", val[:4])
                return val
    except Exception:
        pass

    # Method 2: id-based selectors
    for sel in ["#oauth_pin", "#verifier", "[id*='verifier']", "[id*='oauth_pin']"]:
        try:
            el = page.query_selector(sel)
            if el:
                text = (el.inner_text() or "").strip().replace(" ", "")
                if text and len(text) >= 4:
                    log.info("Verifier found via selector '%s': %s…", sel, text[:4])
                    return text
        except Exception:
            pass

    # Method 3: scan page source for alphanumeric code (4–10 chars) near "verification" keyword
    import re
    content = page.content()
    # Look for the pattern near "verification code" text
    m = re.search(r'[Vv]erification [Cc]ode[^"\'<]*?([A-Z0-9]{4,10})', content)
    if m:
        verifier = m.group(1)
        log.info("Verifier extracted near 'verification code': %s…", verifier[:4])
        return verifier

    # Method 4: broader scan — short uppercase alphanum standalone tokens
    matches = re.findall(r'\bvalue="([A-Z0-9]{4,10})\s*"', content)
    if matches:
        log.info("Verifier from value= scan: %s…", matches[0][:4])
        return matches[0].strip()

    return None


def _dump_page(page, label: str):
    """Save a debug snapshot of the current page for troubleshooting."""
    out_dir = Path(__file__).parent / "debug"
    out_dir.mkdir(exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    html_path = out_dir / f"{label}_{ts}.html"
    png_path  = out_dir / f"{label}_{ts}.png"
    html_path.write_text(page.content(), encoding="utf-8")
    page.screenshot(path=str(png_path))
    log.warning("Debug snapshot saved: %s, %s", html_path, png_path)


# ---------------------------------------------------------------------------
# Step 4: Exchange verifier for access token
# ---------------------------------------------------------------------------

def exchange_for_access_token(req_token: str, req_secret: str, verifier: str) -> tuple[str, str]:
    log.info("Exchanging verifier for access token...")
    auth = OAuth1(
        CONSUMER_KEY,
        CONSUMER_SECRET,
        req_token,
        req_secret,
        verifier=verifier,
    )
    resp = requests.get(ACCESS_TOKEN_URL, auth=auth, timeout=30)
    if resp.status_code != 200:
        log.error("Access token exchange failed: %s %s", resp.status_code, resp.text)
        sys.exit(1)

    from urllib.parse import parse_qs
    params = {k: v[0] for k, v in parse_qs(resp.text).items()}
    access_token  = params["oauth_token"]
    access_secret = params["oauth_token_secret"]
    log.info("Access token obtained: %s…", access_token[:8])
    return access_token, access_secret


# ---------------------------------------------------------------------------
# Step 5: Save token to file
# ---------------------------------------------------------------------------

def save_token(access_token: str, access_secret: str):
    payload = {
        "consumer_key":    CONSUMER_KEY,
        "consumer_secret": CONSUMER_SECRET,
        "access_token":    access_token,
        "access_secret":   access_secret,
        "obtained_at":     datetime.now(timezone.utc).isoformat(),
        "sandbox":         SANDBOX,
    }
    Path(TOKEN_FILE).write_text(json.dumps(payload, indent=2), encoding="utf-8")
    log.info("Token saved to: %s", TOKEN_FILE)


# ---------------------------------------------------------------------------
# Helper: read saved token (for use by your pipeline)
# ---------------------------------------------------------------------------

def load_token(path: str = TOKEN_FILE) -> dict:
    """
    Call this from your pipeline to get a valid OAuth1 session.

    Example:
        from etrade_auth import load_token
        from requests_oauthlib import OAuth1Session

        t = load_token()
        session = OAuth1Session(
            t["consumer_key"], t["consumer_secret"],
            t["access_token"], t["access_secret"],
        )
        resp = session.get("https://api.etrade.com/v1/accounts/list")
    """
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    return data


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    log.info("=== E*TRADE Auth Script ===")
    validate_config()

    # Step 1: Request token
    req_token, req_secret = get_request_token()

    # Step 2: Generate VIP code
    vip_code = get_vip_code()

    # Step 3: Browser automation → verifier
    verifier = browser_authorize(req_token, vip_code)
    log.info("Verifier captured: %s…", verifier[:4])

    # Step 4: Exchange verifier → access token
    access_token, access_secret = exchange_for_access_token(req_token, req_secret, verifier)

    # Step 5: Save
    save_token(access_token, access_secret)

    log.info("=== Auth complete. Token ready for market open. ===")


if __name__ == "__main__":
    main()
